apiVersion: apps/v1

kind: Deployment

metadata:

  name: web-deployement

  labels:

    app: web

spec:

  replicas: 1

  selector:

    matchLabels:

      app: web

  template:

    metadata:

      labels:

        app: web

    spec:

      terminationGracePeriodSeconds: 1

      containers:

      - name: storage-pod

        image: abhishekambulkar/new1

        imagePullPolicy: Always

        ports:

        - containerPort: 9091
